name: Build and Lint

on:
  pull_request:
    branches: [main]
    paths:
      - 'fusian-web/**'
      - '.github/workflows/build.yml'
  workflow_call:
    inputs:
      static_export:
        description: 'Build for static export (GitHub Pages)'
        required: false
        default: false
        type: boolean

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./fusian-web

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: fusian-web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript check
        run: npx tsc --noEmit

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_BASE_PATH: ${{ inputs.static_export == true && '/fusian' || '' }}

      - name: Upload build artifacts (standard build)
        if: ${{ !inputs.static_export }}
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: fusian-web/.next/
          retention-days: 1

      - name: Upload build artifacts (static export)
        if: ${{ inputs.static_export }}
        uses: actions/upload-artifact@v4
        with:
          name: static-export
          path: fusian-web/out/
          retention-days: 1
